import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pl: {
    // Navigation
    'nav.marketplace': 'Rynek',
    'nav.dashboard': 'Panel',
    'nav.admin': 'Administrator',
    'nav.profile': 'Profil',
    'nav.producerDashboard': 'Panel Producenta',
    'nav.adminPanel': 'Panel Administratora',
    'nav.signOut': 'Wyloguj',
    'nav.signIn': 'Zaloguj',
    
    // Common
    'common.loading': 'Ładowanie...',
    'common.error': 'Błąd',
    'common.success': 'Sukces',
    'common.save': 'Zapisz',
    'common.cancel': 'Anuluj',
    'common.delete': 'Usuń',
    'common.edit': 'Edytuj',
    'common.add': 'Dodaj',
    'common.search': 'Szukaj',
    'common.filter': 'Filtruj',
    'common.back': 'Wróć',
    'common.next': 'Dalej',
    'common.previous': 'Poprzedni',
    'common.submit': 'Wyślij',
    'common.close': 'Zamknij',
    'common.open': 'Otwórz',
    'common.yes': 'Tak',
    'common.no': 'Nie',
    'common.optional': 'opcjonalne',
    'common.selectRating': 'Wybierz ocenę',
    'common.mustBeLoggedIn': 'Musisz być zalogowany',
    'common.pleaseLogIn': 'Zaloguj się aby kontynuować',
    'common.submitting': 'Wysyłanie...',
    'common.failedToSubmit': 'Nie udało się wysłać',
    'common.thankYouForFeedback': 'Dziękujemy za opinię!',
    'common.reviewSubmitted': 'Opinia została wysłana',
    'common.producerReviewSubmitted': 'Opinia o producencie została wysłana',
    'common.shareExperience': 'Podziel się swoim doświadczeniem',
    'common.shareExperienceWithProduct': 'Podziel się swoim doświadczeniem z tym produktem...',
    'common.shareExperienceWithProducer': 'Podziel się swoim doświadczeniem z tym producentem...',
    'common.pageNotFound': 'Strona nie została znaleziona',
    'common.returnToHome': 'Powrót do strony głównej',
    'common.oops': 'Ups!',
    
    // Pricing
    'pricing.breakdown': 'Podział zarobków',
    'pricing.customerPrice': 'Cena dla klienta:',
    'pricing.platformCommission': 'Prowizja platformy',
    'pricing.yourEarnings': 'Twoje zarobki:',
    
    // Reviews
    'reviews.leaveReview': 'Zostaw opinię',
    'reviews.rateProducer': 'Oceń tego producenta',
    'reviews.rating': 'Ocena',
    'reviews.comment': 'Komentarz',
    'reviews.pleaseLogInToReview': 'Zaloguj się aby zostawić opinię.',
    'reviews.pleaseLogInToRate': 'Zaloguj się aby ocenić producenta.',
    
    // Welcome
    'welcome.title': 'Witaj w LocalHarvest Hub',
    'welcome.subtitle': 'Zacznij budować swój niesamowity projekt tutaj!',
    
    // Auth
    'auth.signIn': 'Zaloguj się',
    'auth.signUp': 'Zarejestruj się',
    'auth.email': 'E-mail',
    'auth.password': 'Hasło',
    'auth.confirmPassword': 'Potwierdź hasło',
    'auth.fullName': 'Imię i nazwisko',
    'auth.forgotPassword': 'Zapomniałeś hasła?',
    'auth.createAccount': 'Utwórz konto',
    'auth.alreadyHaveAccount': 'Masz już konto?',
    
    // Producer Dashboard
    'producer.dashboard': 'Panel Producenta',
    'producer.welcome': 'Witaj ponownie',
    'producer.addProduct': 'Dodaj Produkt',
    'producer.totalProducts': 'Łączna liczba produktów',
    'producer.totalOrders': 'Łączna liczba zamówień',
    'producer.totalRevenue': 'Łączny przychód',
    'producer.pendingOrders': 'Oczekujące zamówienia',
    'producer.products': 'Produkty',
    'producer.orders': 'Zamówienia',
    'producer.profileSettings': 'Ustawienia profilu',
    'producer.yourProducts': 'Twoje produkty',
    'producer.recentOrders': 'Ostatnie zamówienia',
    'producer.noProducts': 'Brak produktów',
    'producer.noProductsDesc': 'Dodaj swój pierwszy produkt, aby rozpocząć sprzedaż',
    'producer.noOrders': 'Brak zamówień',
    'producer.noOrdersDesc': 'Zamówienia pojawią się tutaj, gdy klienci zaczną kupować Twoje produkty',
    'producer.inStock': 'w magazynie',
    'producer.available': 'Dostępny',
    'producer.unavailable': 'Niedostępny',
    'producer.featured': 'Polecany',
    'producer.acceptOrder': 'Przyjmij zamówienie',
    'producer.declineOrder': 'Odrzuć zamówienie',
    'producer.markCompleted': 'Oznacz jako ukończone',
    'producer.businessName': 'Nazwa firmy',
    'producer.storeStatus': 'Status sklepu',
    'producer.deliveryAvailable': 'Dostawa dostępna',
    'producer.deliveryFee': 'Opłata za dostawę',
    
    // Add Product
    'addProduct.title': 'Dodaj Nowy Produkt',
    'addProduct.description': 'Dodaj swój produkt do marketplace',
    'addProduct.productDetails': 'Szczegóły produktu',
    'addProduct.name': 'Nazwa produktu',
    'addProduct.namePlaceholder': 'np. Świeże pomidory ekologiczne',
    'addProduct.productDescription': 'Opis produktu',
    'addProduct.descriptionPlaceholder': 'Opisz swój produkt...',
    'addProduct.category': 'Kategoria',
    'addProduct.selectCategory': 'Wybierz kategorię',
    'addProduct.image': 'Zdjęcie produktu',
    'addProduct.uploadImage': 'Wgraj zdjęcie',
    'addProduct.changeImage': 'Zmień zdjęcie',
    'addProduct.price': 'Cena',
    'addProduct.pricePlaceholder': '0.00',
    'addProduct.unit': 'Jednostka',
    'addProduct.unitPlaceholder': 'np. kg, szt, l',
    'addProduct.stockQuantity': 'Ilość w magazynie',
    'addProduct.stockPlaceholder': '0',
    'addProduct.madeToOrder': 'Produkt na zamówienie',
    'addProduct.madeToOrderDesc': 'Produkt jest robiony po otrzymaniu zamówienia',
    'addProduct.executionTime': 'Czas wykonania (godziny)',
    'addProduct.executionTimePlaceholder': '24',
    'addProduct.additionalInfo': 'Dodatkowe informacje',
    'addProduct.ingredients': 'Składniki',
    'addProduct.ingredientsPlaceholder': 'Lista składników...',
    'addProduct.allergens': 'Alergeny',
    'addProduct.allergensPlaceholder': 'np. gluten, orzechy...',
    'addProduct.storageInstructions': 'Instrukcje przechowywania',
    'addProduct.storageInstructionsPlaceholder': 'Jak przechowywać produkt...',
    'addProduct.shelfLifeDays': 'Okres przydatności (dni)',
    'addProduct.shelfLifePlaceholder': '7',
    'addProduct.tags': 'Tagi',
    'addProduct.tagsPlaceholder': 'np. ekologiczne, lokalne, sezonowe',
    'addProduct.settings': 'Ustawienia',
    'addProduct.isAvailable': 'Produkt dostępny',
    'addProduct.featured': 'Produkt polecany',
    'addProduct.createProduct': 'Utwórz produkt',
    'addProduct.uploadingImage': 'Wgrywanie zdjęcia...',
    'addProduct.success': 'Produkt został pomyślnie dodany',
    'addProduct.error': 'Błąd podczas dodawania produktu',
    'addProduct.imageError': 'Błąd podczas wgrywania zdjęcia',
    'addProduct.nameRequired': 'Nazwa produktu jest wymagana',
    'addProduct.priceRequired': 'Cena jest wymagana',
    'addProduct.categoryRequired': 'Kategoria jest wymagana',
    'addProduct.unitRequired': 'Jednostka jest wymagana',
    'addProduct.stockRequired': 'Ilość w magazynie jest wymagana',
    'addProduct.executionTimeRequired': 'Czas wykonania jest wymagany dla produktów na zamówienie',
    
    // Admin Dashboard
    'admin.dashboard': 'Panel Administratora',
    'admin.managePlatform': 'Zarządzaj platformą LocalHarvest Hub',
    'admin.administrator': 'Administrator',
    'admin.totalUsers': 'Łączna liczba użytkowników',
    'admin.producers': 'Producenci',
    'admin.totalOrders': 'Łączna liczba zamówień',
    'admin.totalRevenue': 'Łączny przychód',
    'admin.pendingOrders': 'Oczekujące zamówienia',
    'admin.users': 'Użytkownicy',
    'admin.orders': 'Zamówienia',
    'admin.products': 'Produkty',
    'admin.platformSettings': 'Ustawienia platformy',
    'admin.userManagement': 'Zarządzanie użytkownikami',
    'admin.manageUsers': 'Zarządzaj użytkownikami platformy i ich rolami',
    'admin.producerManagement': 'Zarządzanie producentami',
    'admin.manageProducers': 'Zarządzaj producentami żywności i ich sklepami',
    'admin.orderManagement': 'Zarządzanie zamówieniami',
    'admin.manageOrders': 'Monitoruj i zarządzaj zamówieniami platformy',
    'admin.productManagement': 'Zarządzanie produktami',
    'admin.manageProducts': 'Monitoruj produkty platformy i zapasy',
    'admin.name': 'Imię',
    'admin.email': 'E-mail',
    'admin.role': 'Rola',
    'admin.joined': 'Dołączył',
    'admin.actions': 'Akcje',
    'admin.businessName': 'Nazwa firmy',
    'admin.owner': 'Właściciel',
    'admin.status': 'Status',
    'admin.totalSales': 'Łączna sprzedaż',
    'admin.rating': 'Ocena',
    'admin.orderId': 'ID zamówienia',
    'admin.customer': 'Klient',
    'admin.producer': 'Producent',
    'admin.amount': 'Kwota',
    'admin.date': 'Data',
    'admin.product': 'Produkt',
    'admin.category': 'Kategoria',
    'admin.price': 'Cena',
    'admin.stock': 'Magazyn',
    'admin.created': 'Utworzono',
    'admin.consumer': 'Konsument',
    'admin.admin': 'Administrator',
    'admin.open': 'Otwarte',
    'admin.closed': 'Zamknięte',
    'admin.pending': 'Oczekujące',
    'admin.confirmed': 'Potwierdzone',
    'admin.preparing': 'Przygotowywane',
    'admin.ready': 'Gotowe',
    'admin.completed': 'Ukończone',
    'admin.cancelled': 'Anulowane',
    'admin.available': 'Dostępne',
    'admin.unavailable': 'Niedostępne',
    'admin.uncategorized': 'Bez kategorii',
    
    // Marketplace
    'marketplace.title': 'Lokalny Rynek Żywności',
    'marketplace.subtitle': 'Odkryj świeże, lokalne produkty od sprawdzonych producentów',
    'marketplace.searchPlaceholder': 'Szukaj produktów...',
    'marketplace.allCategories': 'Wszystkie kategorie',
    'marketplace.noProducts': 'Nie znaleziono produktów',
    'marketplace.noProductsDesc': 'Spróbuj zmienić filtry lub wyszukać coś innego',
    'marketplace.addToCart': 'Dodaj do koszyka',
    'marketplace.outOfStock': 'Brak w magazynie',
    'marketplace.by': 'przez',
    
    // Order Status
    'order.pending': 'Oczekujące',
    'order.confirmed': 'Potwierdzone',
    'order.preparing': 'Przygotowywane',
    'order.ready': 'Gotowe',
    'order.completed': 'Ukończone',
    'order.cancelled': 'Anulowane',
  },
  en: {
    // Navigation
    'nav.marketplace': 'Marketplace',
    'nav.dashboard': 'Dashboard',
    'nav.admin': 'Admin',
    'nav.profile': 'Profile',
    'nav.producerDashboard': 'Producer Dashboard',
    'nav.adminPanel': 'Admin Panel',
    'nav.signOut': 'Sign Out',
    'nav.signIn': 'Sign In',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.optional': 'optional',
    'common.selectRating': 'Select a rating',
    'common.mustBeLoggedIn': 'You must be logged in',
    'common.pleaseLogIn': 'Please log in to continue',
    'common.submitting': 'Submitting...',
    'common.failedToSubmit': 'Failed to submit',
    'common.thankYouForFeedback': 'Thank you for your feedback!',
    'common.reviewSubmitted': 'Review submitted',
    'common.producerReviewSubmitted': 'Your producer review has been submitted',
    'common.shareExperience': 'Share your experience',
    'common.shareExperienceWithProduct': 'Share your experience with this product...',
    'common.shareExperienceWithProducer': 'Share your experience with this producer...',
    'common.pageNotFound': 'Page not found',
    'common.returnToHome': 'Return to Home',
    'common.oops': 'Oops!',
    
    // Pricing
    'pricing.breakdown': 'Earnings Breakdown',
    'pricing.customerPrice': 'Customer Price:',
    'pricing.platformCommission': 'Platform Commission',
    'pricing.yourEarnings': 'Your Earnings:',
    
    // Reviews
    'reviews.leaveReview': 'Leave a Review',
    'reviews.rateProducer': 'Rate this Producer',
    'reviews.rating': 'Rating',
    'reviews.comment': 'Comment',
    'reviews.pleaseLogInToReview': 'Please log in to leave a review.',
    'reviews.pleaseLogInToRate': 'Please log in to rate the producer.',
    
    // Welcome
    'welcome.title': 'Welcome to LocalHarvest Hub',
    'welcome.subtitle': 'Start building your amazing project here!',
    
    // Auth
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.createAccount': 'Create Account',
    'auth.alreadyHaveAccount': 'Already have an account?',
    
    // Producer Dashboard
    'producer.dashboard': 'Producer Dashboard',
    'producer.welcome': 'Welcome back',
    'producer.addProduct': 'Add Product',
    'producer.totalProducts': 'Total Products',
    'producer.totalOrders': 'Total Orders',
    'producer.totalRevenue': 'Total Revenue',
    'producer.pendingOrders': 'Pending Orders',
    'producer.products': 'Products',
    'producer.orders': 'Orders',
    'producer.profileSettings': 'Profile Settings',
    'producer.yourProducts': 'Your Products',
    'producer.recentOrders': 'Recent Orders',
    'producer.noProducts': 'No products yet',
    'producer.noProductsDesc': 'Add your first product to start selling',
    'producer.noOrders': 'No orders yet',
    'producer.noOrdersDesc': 'Orders will appear here when customers start purchasing your products',
    'producer.inStock': 'in stock',
    'producer.available': 'Available',
    'producer.unavailable': 'Unavailable',
    'producer.featured': 'Featured',
    'producer.acceptOrder': 'Accept Order',
    'producer.declineOrder': 'Decline Order',
    'producer.markCompleted': 'Mark as Completed',
    'producer.businessName': 'Business Name',
    'producer.storeStatus': 'Store Status',
    'producer.deliveryAvailable': 'Delivery Available',
    'producer.deliveryFee': 'Delivery Fee',
    
    // Add Product
    'addProduct.title': 'Add New Product',
    'addProduct.description': 'Add your product to the marketplace',
    'addProduct.productDetails': 'Product Details',
    'addProduct.name': 'Product Name',
    'addProduct.namePlaceholder': 'e.g. Organic Fresh Tomatoes',
    'addProduct.productDescription': 'Product Description',
    'addProduct.descriptionPlaceholder': 'Describe your product...',
    'addProduct.category': 'Category',
    'addProduct.selectCategory': 'Select category',
    'addProduct.price': 'Price',
    'addProduct.pricePlaceholder': '0.00',
    'addProduct.unit': 'Unit',
    'addProduct.unitPlaceholder': 'e.g. kg, pcs, l',
    'addProduct.stockQuantity': 'Stock Quantity',
    'addProduct.stockPlaceholder': '0',
    'addProduct.additionalInfo': 'Additional Information',
    'addProduct.ingredients': 'Ingredients',
    'addProduct.ingredientsPlaceholder': 'List of ingredients...',
    'addProduct.allergens': 'Allergens',
    'addProduct.allergensPlaceholder': 'e.g. gluten, nuts...',
    'addProduct.storageInstructions': 'Storage Instructions',
    'addProduct.storageInstructionsPlaceholder': 'How to store the product...',
    'addProduct.shelfLifeDays': 'Shelf Life (days)',
    'addProduct.shelfLifePlaceholder': '7',
    'addProduct.tags': 'Tags',
    'addProduct.tagsPlaceholder': 'e.g. organic, local, seasonal',
    'addProduct.settings': 'Settings',
    'addProduct.isAvailable': 'Product Available',
    'addProduct.featured': 'Featured Product',
    'addProduct.createProduct': 'Create Product',
    'addProduct.success': 'Product added successfully',
    'addProduct.error': 'Error adding product',
    'addProduct.nameRequired': 'Product name is required',
    'addProduct.priceRequired': 'Price is required',
    'addProduct.categoryRequired': 'Category is required',
    'addProduct.unitRequired': 'Unit is required',
    'addProduct.stockRequired': 'Stock quantity is required',
    
    // Admin Dashboard
    'admin.dashboard': 'Admin Dashboard',
    'admin.managePlatform': 'Manage your LocalHarvest Hub platform',
    'admin.administrator': 'Administrator',
    'admin.totalUsers': 'Total Users',
    'admin.producers': 'Producers',
    'admin.totalOrders': 'Total Orders',
    'admin.totalRevenue': 'Total Revenue',
    'admin.pendingOrders': 'Pending Orders',
    'admin.users': 'Users',
    'admin.orders': 'Orders',
    'admin.products': 'Products',
    'admin.platformSettings': 'Platform Settings',
    'admin.userManagement': 'User Management',
    'admin.manageUsers': 'Manage platform users and their roles',
    'admin.producerManagement': 'Producer Management',
    'admin.manageProducers': 'Manage food producers and their stores',
    'admin.orderManagement': 'Order Management',
    'admin.manageOrders': 'Monitor and manage platform orders',
    'admin.productManagement': 'Product Management',
    'admin.manageProducts': 'Monitor platform products and inventory',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.role': 'Role',
    'admin.joined': 'Joined',
    'admin.actions': 'Actions',
    'admin.businessName': 'Business Name',
    'admin.owner': 'Owner',
    'admin.status': 'Status',
    'admin.totalSales': 'Total Sales',
    'admin.rating': 'Rating',
    'admin.orderId': 'Order ID',
    'admin.customer': 'Customer',
    'admin.producer': 'Producer',
    'admin.amount': 'Amount',
    'admin.date': 'Date',
    'admin.product': 'Product',
    'admin.category': 'Category',
    'admin.price': 'Price',
    'admin.stock': 'Stock',
    'admin.created': 'Created',
    'admin.consumer': 'Consumer',
    'admin.admin': 'Admin',
    'admin.open': 'Open',
    'admin.closed': 'Closed',
    'admin.pending': 'Pending',
    'admin.confirmed': 'Confirmed',
    'admin.preparing': 'Preparing',
    'admin.ready': 'Ready',
    'admin.completed': 'Completed',
    'admin.cancelled': 'Cancelled',
    'admin.available': 'Available',
    'admin.unavailable': 'Unavailable',
    'admin.uncategorized': 'Uncategorized',
    
    // Marketplace
    'marketplace.title': 'Local Food Marketplace',
    'marketplace.subtitle': 'Discover fresh, local products from trusted producers',
    'marketplace.searchPlaceholder': 'Search products...',
    'marketplace.allCategories': 'All Categories',
    'marketplace.noProducts': 'No products found',
    'marketplace.noProductsDesc': 'Try changing your filters or search for something else',
    'marketplace.addToCart': 'Add to Cart',
    'marketplace.outOfStock': 'Out of Stock',
    'marketplace.by': 'by',
    
    // Order Status
    'order.pending': 'Pending',
    'order.confirmed': 'Confirmed',
    'order.preparing': 'Preparing',
    'order.ready': 'Ready',
    'order.completed': 'Completed',
    'order.cancelled': 'Cancelled',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'pl';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    const langTranslations = translations[language as keyof typeof translations] || translations.pl;
    return langTranslations[key as keyof typeof langTranslations] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};