// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oevnfnlltrfupwmtfmmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ldm5mbmxsdHJmdXB3bXRmbW1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzMzNTIsImV4cCI6MjA3MDI0OTM1Mn0.AjSckgWlEYJ8k9-rs2XEonL_HTTUVxM49M-qZzPNbMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});